#!/bin/bash

server_file=$1

echo "Starting run" > deploy.log
echo "" > pids.txt

while read -r line; do
  hostArr=(${line//:/ })

  java -Xmx512m -jar A9.jar -s $server_file -p ${hostArr[1]} > "logs/${hostArr[0]}.${hostArr[1]}.log" &
  echo "Started ${hostArr[0]}:${hostArr[1]} with pid $!" >> deploy.log
  echo "$!" >> pids.txt
  echo "Started ${hostArr[0]}:${hostArr[1]} with pid $!"
done < $server_file
