// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protobuf/InternalRequest.proto

package ca.NetSysLab.ProtocolBuffers;

public final class InternalRequest {
  private InternalRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HostOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Host)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes ip = 1;</code>
     * @return The ip.
     */
    com.google.protobuf.ByteString getIp();

    /**
     * <code>int32 port = 2;</code>
     * @return The port.
     */
    int getPort();
  }
  /**
   * Protobuf type {@code Host}
   */
  public static final class Host extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Host)
      HostOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Host.newBuilder() to construct.
    private Host(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Host() {
      ip_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Host();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.NetSysLab.ProtocolBuffers.InternalRequest.internal_static_Host_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.NetSysLab.ProtocolBuffers.InternalRequest.internal_static_Host_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.NetSysLab.ProtocolBuffers.InternalRequest.Host.class, ca.NetSysLab.ProtocolBuffers.InternalRequest.Host.Builder.class);
    }

    public static final int IP_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString ip_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes ip = 1;</code>
     * @return The ip.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getIp() {
      return ip_;
    }

    public static final int PORT_FIELD_NUMBER = 2;
    private int port_ = 0;
    /**
     * <code>int32 port = 2;</code>
     * @return The port.
     */
    @java.lang.Override
    public int getPort() {
      return port_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!ip_.isEmpty()) {
        output.writeBytes(1, ip_);
      }
      if (port_ != 0) {
        output.writeInt32(2, port_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!ip_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, ip_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, port_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ca.NetSysLab.ProtocolBuffers.InternalRequest.Host)) {
        return super.equals(obj);
      }
      ca.NetSysLab.ProtocolBuffers.InternalRequest.Host other = (ca.NetSysLab.ProtocolBuffers.InternalRequest.Host) obj;

      if (!getIp()
          .equals(other.getIp())) return false;
      if (getPort()
          != other.getPort()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.Host parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.Host parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.Host parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.Host parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.Host parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.Host parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.Host parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.Host parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.Host parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.Host parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.Host parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.Host parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ca.NetSysLab.ProtocolBuffers.InternalRequest.Host prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Host}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Host)
        ca.NetSysLab.ProtocolBuffers.InternalRequest.HostOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ca.NetSysLab.ProtocolBuffers.InternalRequest.internal_static_Host_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ca.NetSysLab.ProtocolBuffers.InternalRequest.internal_static_Host_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ca.NetSysLab.ProtocolBuffers.InternalRequest.Host.class, ca.NetSysLab.ProtocolBuffers.InternalRequest.Host.Builder.class);
      }

      // Construct using ca.NetSysLab.ProtocolBuffers.InternalRequest.Host.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        ip_ = com.google.protobuf.ByteString.EMPTY;
        port_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.NetSysLab.ProtocolBuffers.InternalRequest.internal_static_Host_descriptor;
      }

      @java.lang.Override
      public ca.NetSysLab.ProtocolBuffers.InternalRequest.Host getDefaultInstanceForType() {
        return ca.NetSysLab.ProtocolBuffers.InternalRequest.Host.getDefaultInstance();
      }

      @java.lang.Override
      public ca.NetSysLab.ProtocolBuffers.InternalRequest.Host build() {
        ca.NetSysLab.ProtocolBuffers.InternalRequest.Host result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ca.NetSysLab.ProtocolBuffers.InternalRequest.Host buildPartial() {
        ca.NetSysLab.ProtocolBuffers.InternalRequest.Host result = new ca.NetSysLab.ProtocolBuffers.InternalRequest.Host(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ca.NetSysLab.ProtocolBuffers.InternalRequest.Host result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.ip_ = ip_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.port_ = port_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.NetSysLab.ProtocolBuffers.InternalRequest.Host) {
          return mergeFrom((ca.NetSysLab.ProtocolBuffers.InternalRequest.Host)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ca.NetSysLab.ProtocolBuffers.InternalRequest.Host other) {
        if (other == ca.NetSysLab.ProtocolBuffers.InternalRequest.Host.getDefaultInstance()) return this;
        if (other.getIp() != com.google.protobuf.ByteString.EMPTY) {
          setIp(other.getIp());
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                ip_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                port_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString ip_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes ip = 1;</code>
       * @return The ip.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getIp() {
        return ip_;
      }
      /**
       * <code>bytes ip = 1;</code>
       * @param value The ip to set.
       * @return This builder for chaining.
       */
      public Builder setIp(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ip_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bytes ip = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>int32 port = 2;</code>
       * @return The port.
       */
      @java.lang.Override
      public int getPort() {
        return port_;
      }
      /**
       * <code>int32 port = 2;</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(int value) {
        
        port_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 port = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000002);
        port_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Host)
    }

    // @@protoc_insertion_point(class_scope:Host)
    private static final ca.NetSysLab.ProtocolBuffers.InternalRequest.Host DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ca.NetSysLab.ProtocolBuffers.InternalRequest.Host();
    }

    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.Host getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Host>
        PARSER = new com.google.protobuf.AbstractParser<Host>() {
      @java.lang.Override
      public Host parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Host> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Host> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ca.NetSysLab.ProtocolBuffers.InternalRequest.Host getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeartbeatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Heartbeat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Host host = 1;</code>
     * @return Whether the host field is set.
     */
    boolean hasHost();
    /**
     * <code>.Host host = 1;</code>
     * @return The host.
     */
    ca.NetSysLab.ProtocolBuffers.InternalRequest.Host getHost();
    /**
     * <code>.Host host = 1;</code>
     */
    ca.NetSysLab.ProtocolBuffers.InternalRequest.HostOrBuilder getHostOrBuilder();

    /**
     * <code>int32 id = 2;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>int64 epochMillis = 3;</code>
     * @return The epochMillis.
     */
    long getEpochMillis();
  }
  /**
   * Protobuf type {@code Heartbeat}
   */
  public static final class Heartbeat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Heartbeat)
      HeartbeatOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Heartbeat.newBuilder() to construct.
    private Heartbeat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Heartbeat() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Heartbeat();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.NetSysLab.ProtocolBuffers.InternalRequest.internal_static_Heartbeat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.NetSysLab.ProtocolBuffers.InternalRequest.internal_static_Heartbeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat.class, ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat.Builder.class);
    }

    public static final int HOST_FIELD_NUMBER = 1;
    private ca.NetSysLab.ProtocolBuffers.InternalRequest.Host host_;
    /**
     * <code>.Host host = 1;</code>
     * @return Whether the host field is set.
     */
    @java.lang.Override
    public boolean hasHost() {
      return host_ != null;
    }
    /**
     * <code>.Host host = 1;</code>
     * @return The host.
     */
    @java.lang.Override
    public ca.NetSysLab.ProtocolBuffers.InternalRequest.Host getHost() {
      return host_ == null ? ca.NetSysLab.ProtocolBuffers.InternalRequest.Host.getDefaultInstance() : host_;
    }
    /**
     * <code>.Host host = 1;</code>
     */
    @java.lang.Override
    public ca.NetSysLab.ProtocolBuffers.InternalRequest.HostOrBuilder getHostOrBuilder() {
      return host_ == null ? ca.NetSysLab.ProtocolBuffers.InternalRequest.Host.getDefaultInstance() : host_;
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_ = 0;
    /**
     * <code>int32 id = 2;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int EPOCHMILLIS_FIELD_NUMBER = 3;
    private long epochMillis_ = 0L;
    /**
     * <code>int64 epochMillis = 3;</code>
     * @return The epochMillis.
     */
    @java.lang.Override
    public long getEpochMillis() {
      return epochMillis_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (host_ != null) {
        output.writeMessage(1, getHost());
      }
      if (id_ != 0) {
        output.writeInt32(2, id_);
      }
      if (epochMillis_ != 0L) {
        output.writeInt64(3, epochMillis_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (host_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHost());
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (epochMillis_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, epochMillis_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat)) {
        return super.equals(obj);
      }
      ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat other = (ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat) obj;

      if (hasHost() != other.hasHost()) return false;
      if (hasHost()) {
        if (!getHost()
            .equals(other.getHost())) return false;
      }
      if (getId()
          != other.getId()) return false;
      if (getEpochMillis()
          != other.getEpochMillis()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHost()) {
        hash = (37 * hash) + HOST_FIELD_NUMBER;
        hash = (53 * hash) + getHost().hashCode();
      }
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + EPOCHMILLIS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getEpochMillis());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Heartbeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Heartbeat)
        ca.NetSysLab.ProtocolBuffers.InternalRequest.HeartbeatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ca.NetSysLab.ProtocolBuffers.InternalRequest.internal_static_Heartbeat_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ca.NetSysLab.ProtocolBuffers.InternalRequest.internal_static_Heartbeat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat.class, ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat.Builder.class);
      }

      // Construct using ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        host_ = null;
        if (hostBuilder_ != null) {
          hostBuilder_.dispose();
          hostBuilder_ = null;
        }
        id_ = 0;
        epochMillis_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.NetSysLab.ProtocolBuffers.InternalRequest.internal_static_Heartbeat_descriptor;
      }

      @java.lang.Override
      public ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat getDefaultInstanceForType() {
        return ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat.getDefaultInstance();
      }

      @java.lang.Override
      public ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat build() {
        ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat buildPartial() {
        ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat result = new ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.host_ = hostBuilder_ == null
              ? host_
              : hostBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.epochMillis_ = epochMillis_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat) {
          return mergeFrom((ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat other) {
        if (other == ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat.getDefaultInstance()) return this;
        if (other.hasHost()) {
          mergeHost(other.getHost());
        }
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getEpochMillis() != 0L) {
          setEpochMillis(other.getEpochMillis());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getHostFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                epochMillis_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private ca.NetSysLab.ProtocolBuffers.InternalRequest.Host host_;
      private com.google.protobuf.SingleFieldBuilderV3<
          ca.NetSysLab.ProtocolBuffers.InternalRequest.Host, ca.NetSysLab.ProtocolBuffers.InternalRequest.Host.Builder, ca.NetSysLab.ProtocolBuffers.InternalRequest.HostOrBuilder> hostBuilder_;
      /**
       * <code>.Host host = 1;</code>
       * @return Whether the host field is set.
       */
      public boolean hasHost() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.Host host = 1;</code>
       * @return The host.
       */
      public ca.NetSysLab.ProtocolBuffers.InternalRequest.Host getHost() {
        if (hostBuilder_ == null) {
          return host_ == null ? ca.NetSysLab.ProtocolBuffers.InternalRequest.Host.getDefaultInstance() : host_;
        } else {
          return hostBuilder_.getMessage();
        }
      }
      /**
       * <code>.Host host = 1;</code>
       */
      public Builder setHost(ca.NetSysLab.ProtocolBuffers.InternalRequest.Host value) {
        if (hostBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          host_ = value;
        } else {
          hostBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.Host host = 1;</code>
       */
      public Builder setHost(
          ca.NetSysLab.ProtocolBuffers.InternalRequest.Host.Builder builderForValue) {
        if (hostBuilder_ == null) {
          host_ = builderForValue.build();
        } else {
          hostBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.Host host = 1;</code>
       */
      public Builder mergeHost(ca.NetSysLab.ProtocolBuffers.InternalRequest.Host value) {
        if (hostBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            host_ != null &&
            host_ != ca.NetSysLab.ProtocolBuffers.InternalRequest.Host.getDefaultInstance()) {
            getHostBuilder().mergeFrom(value);
          } else {
            host_ = value;
          }
        } else {
          hostBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.Host host = 1;</code>
       */
      public Builder clearHost() {
        bitField0_ = (bitField0_ & ~0x00000001);
        host_ = null;
        if (hostBuilder_ != null) {
          hostBuilder_.dispose();
          hostBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.Host host = 1;</code>
       */
      public ca.NetSysLab.ProtocolBuffers.InternalRequest.Host.Builder getHostBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHostFieldBuilder().getBuilder();
      }
      /**
       * <code>.Host host = 1;</code>
       */
      public ca.NetSysLab.ProtocolBuffers.InternalRequest.HostOrBuilder getHostOrBuilder() {
        if (hostBuilder_ != null) {
          return hostBuilder_.getMessageOrBuilder();
        } else {
          return host_ == null ?
              ca.NetSysLab.ProtocolBuffers.InternalRequest.Host.getDefaultInstance() : host_;
        }
      }
      /**
       * <code>.Host host = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ca.NetSysLab.ProtocolBuffers.InternalRequest.Host, ca.NetSysLab.ProtocolBuffers.InternalRequest.Host.Builder, ca.NetSysLab.ProtocolBuffers.InternalRequest.HostOrBuilder> 
          getHostFieldBuilder() {
        if (hostBuilder_ == null) {
          hostBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ca.NetSysLab.ProtocolBuffers.InternalRequest.Host, ca.NetSysLab.ProtocolBuffers.InternalRequest.Host.Builder, ca.NetSysLab.ProtocolBuffers.InternalRequest.HostOrBuilder>(
                  getHost(),
                  getParentForChildren(),
                  isClean());
          host_ = null;
        }
        return hostBuilder_;
      }

      private int id_ ;
      /**
       * <code>int32 id = 2;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 2;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      private long epochMillis_ ;
      /**
       * <code>int64 epochMillis = 3;</code>
       * @return The epochMillis.
       */
      @java.lang.Override
      public long getEpochMillis() {
        return epochMillis_;
      }
      /**
       * <code>int64 epochMillis = 3;</code>
       * @param value The epochMillis to set.
       * @return This builder for chaining.
       */
      public Builder setEpochMillis(long value) {
        
        epochMillis_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int64 epochMillis = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEpochMillis() {
        bitField0_ = (bitField0_ & ~0x00000004);
        epochMillis_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Heartbeat)
    }

    // @@protoc_insertion_point(class_scope:Heartbeat)
    private static final ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat();
    }

    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Heartbeat>
        PARSER = new com.google.protobuf.AbstractParser<Heartbeat>() {
      @java.lang.Override
      public Heartbeat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Heartbeat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Heartbeat> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface InternalRequestWrapperOrBuilder extends
      // @@protoc_insertion_point(interface_extends:InternalRequestWrapper)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .Host client = 1;</code>
     * @return Whether the client field is set.
     */
    boolean hasClient();
    /**
     * <code>optional .Host client = 1;</code>
     * @return The client.
     */
    ca.NetSysLab.ProtocolBuffers.InternalRequest.Host getClient();
    /**
     * <code>optional .Host client = 1;</code>
     */
    ca.NetSysLab.ProtocolBuffers.InternalRequest.HostOrBuilder getClientOrBuilder();

    /**
     * <code>optional .KVRequest request = 2;</code>
     * @return Whether the request field is set.
     */
    boolean hasRequest();
    /**
     * <code>optional .KVRequest request = 2;</code>
     * @return The request.
     */
    ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest getRequest();
    /**
     * <code>optional .KVRequest request = 2;</code>
     */
    ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequestOrBuilder getRequestOrBuilder();

    /**
     * <code>repeated .Heartbeat heartbeats = 3;</code>
     */
    java.util.List<ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat> 
        getHeartbeatsList();
    /**
     * <code>repeated .Heartbeat heartbeats = 3;</code>
     */
    ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat getHeartbeats(int index);
    /**
     * <code>repeated .Heartbeat heartbeats = 3;</code>
     */
    int getHeartbeatsCount();
    /**
     * <code>repeated .Heartbeat heartbeats = 3;</code>
     */
    java.util.List<? extends ca.NetSysLab.ProtocolBuffers.InternalRequest.HeartbeatOrBuilder> 
        getHeartbeatsOrBuilderList();
    /**
     * <code>repeated .Heartbeat heartbeats = 3;</code>
     */
    ca.NetSysLab.ProtocolBuffers.InternalRequest.HeartbeatOrBuilder getHeartbeatsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code InternalRequestWrapper}
   */
  public static final class InternalRequestWrapper extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:InternalRequestWrapper)
      InternalRequestWrapperOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InternalRequestWrapper.newBuilder() to construct.
    private InternalRequestWrapper(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InternalRequestWrapper() {
      heartbeats_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new InternalRequestWrapper();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.NetSysLab.ProtocolBuffers.InternalRequest.internal_static_InternalRequestWrapper_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.NetSysLab.ProtocolBuffers.InternalRequest.internal_static_InternalRequestWrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper.class, ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper.Builder.class);
    }

    private int bitField0_;
    public static final int CLIENT_FIELD_NUMBER = 1;
    private ca.NetSysLab.ProtocolBuffers.InternalRequest.Host client_;
    /**
     * <code>optional .Host client = 1;</code>
     * @return Whether the client field is set.
     */
    @java.lang.Override
    public boolean hasClient() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .Host client = 1;</code>
     * @return The client.
     */
    @java.lang.Override
    public ca.NetSysLab.ProtocolBuffers.InternalRequest.Host getClient() {
      return client_ == null ? ca.NetSysLab.ProtocolBuffers.InternalRequest.Host.getDefaultInstance() : client_;
    }
    /**
     * <code>optional .Host client = 1;</code>
     */
    @java.lang.Override
    public ca.NetSysLab.ProtocolBuffers.InternalRequest.HostOrBuilder getClientOrBuilder() {
      return client_ == null ? ca.NetSysLab.ProtocolBuffers.InternalRequest.Host.getDefaultInstance() : client_;
    }

    public static final int REQUEST_FIELD_NUMBER = 2;
    private ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest request_;
    /**
     * <code>optional .KVRequest request = 2;</code>
     * @return Whether the request field is set.
     */
    @java.lang.Override
    public boolean hasRequest() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .KVRequest request = 2;</code>
     * @return The request.
     */
    @java.lang.Override
    public ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest getRequest() {
      return request_ == null ? ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest.getDefaultInstance() : request_;
    }
    /**
     * <code>optional .KVRequest request = 2;</code>
     */
    @java.lang.Override
    public ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequestOrBuilder getRequestOrBuilder() {
      return request_ == null ? ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest.getDefaultInstance() : request_;
    }

    public static final int HEARTBEATS_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private java.util.List<ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat> heartbeats_;
    /**
     * <code>repeated .Heartbeat heartbeats = 3;</code>
     */
    @java.lang.Override
    public java.util.List<ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat> getHeartbeatsList() {
      return heartbeats_;
    }
    /**
     * <code>repeated .Heartbeat heartbeats = 3;</code>
     */
    @java.lang.Override
    public java.util.List<? extends ca.NetSysLab.ProtocolBuffers.InternalRequest.HeartbeatOrBuilder> 
        getHeartbeatsOrBuilderList() {
      return heartbeats_;
    }
    /**
     * <code>repeated .Heartbeat heartbeats = 3;</code>
     */
    @java.lang.Override
    public int getHeartbeatsCount() {
      return heartbeats_.size();
    }
    /**
     * <code>repeated .Heartbeat heartbeats = 3;</code>
     */
    @java.lang.Override
    public ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat getHeartbeats(int index) {
      return heartbeats_.get(index);
    }
    /**
     * <code>repeated .Heartbeat heartbeats = 3;</code>
     */
    @java.lang.Override
    public ca.NetSysLab.ProtocolBuffers.InternalRequest.HeartbeatOrBuilder getHeartbeatsOrBuilder(
        int index) {
      return heartbeats_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getClient());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getRequest());
      }
      for (int i = 0; i < heartbeats_.size(); i++) {
        output.writeMessage(3, heartbeats_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getClient());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getRequest());
      }
      for (int i = 0; i < heartbeats_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, heartbeats_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper)) {
        return super.equals(obj);
      }
      ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper other = (ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper) obj;

      if (hasClient() != other.hasClient()) return false;
      if (hasClient()) {
        if (!getClient()
            .equals(other.getClient())) return false;
      }
      if (hasRequest() != other.hasRequest()) return false;
      if (hasRequest()) {
        if (!getRequest()
            .equals(other.getRequest())) return false;
      }
      if (!getHeartbeatsList()
          .equals(other.getHeartbeatsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasClient()) {
        hash = (37 * hash) + CLIENT_FIELD_NUMBER;
        hash = (53 * hash) + getClient().hashCode();
      }
      if (hasRequest()) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
      }
      if (getHeartbeatsCount() > 0) {
        hash = (37 * hash) + HEARTBEATS_FIELD_NUMBER;
        hash = (53 * hash) + getHeartbeatsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code InternalRequestWrapper}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:InternalRequestWrapper)
        ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ca.NetSysLab.ProtocolBuffers.InternalRequest.internal_static_InternalRequestWrapper_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ca.NetSysLab.ProtocolBuffers.InternalRequest.internal_static_InternalRequestWrapper_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper.class, ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper.Builder.class);
      }

      // Construct using ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getClientFieldBuilder();
          getRequestFieldBuilder();
          getHeartbeatsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        client_ = null;
        if (clientBuilder_ != null) {
          clientBuilder_.dispose();
          clientBuilder_ = null;
        }
        request_ = null;
        if (requestBuilder_ != null) {
          requestBuilder_.dispose();
          requestBuilder_ = null;
        }
        if (heartbeatsBuilder_ == null) {
          heartbeats_ = java.util.Collections.emptyList();
        } else {
          heartbeats_ = null;
          heartbeatsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.NetSysLab.ProtocolBuffers.InternalRequest.internal_static_InternalRequestWrapper_descriptor;
      }

      @java.lang.Override
      public ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper getDefaultInstanceForType() {
        return ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper.getDefaultInstance();
      }

      @java.lang.Override
      public ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper build() {
        ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper buildPartial() {
        ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper result = new ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper result) {
        if (heartbeatsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0)) {
            heartbeats_ = java.util.Collections.unmodifiableList(heartbeats_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.heartbeats_ = heartbeats_;
        } else {
          result.heartbeats_ = heartbeatsBuilder_.build();
        }
      }

      private void buildPartial0(ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.client_ = clientBuilder_ == null
              ? client_
              : clientBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.request_ = requestBuilder_ == null
              ? request_
              : requestBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper) {
          return mergeFrom((ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper other) {
        if (other == ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper.getDefaultInstance()) return this;
        if (other.hasClient()) {
          mergeClient(other.getClient());
        }
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (heartbeatsBuilder_ == null) {
          if (!other.heartbeats_.isEmpty()) {
            if (heartbeats_.isEmpty()) {
              heartbeats_ = other.heartbeats_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureHeartbeatsIsMutable();
              heartbeats_.addAll(other.heartbeats_);
            }
            onChanged();
          }
        } else {
          if (!other.heartbeats_.isEmpty()) {
            if (heartbeatsBuilder_.isEmpty()) {
              heartbeatsBuilder_.dispose();
              heartbeatsBuilder_ = null;
              heartbeats_ = other.heartbeats_;
              bitField0_ = (bitField0_ & ~0x00000004);
              heartbeatsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getHeartbeatsFieldBuilder() : null;
            } else {
              heartbeatsBuilder_.addAllMessages(other.heartbeats_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getClientFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getRequestFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat m =
                    input.readMessage(
                        ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat.parser(),
                        extensionRegistry);
                if (heartbeatsBuilder_ == null) {
                  ensureHeartbeatsIsMutable();
                  heartbeats_.add(m);
                } else {
                  heartbeatsBuilder_.addMessage(m);
                }
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private ca.NetSysLab.ProtocolBuffers.InternalRequest.Host client_;
      private com.google.protobuf.SingleFieldBuilderV3<
          ca.NetSysLab.ProtocolBuffers.InternalRequest.Host, ca.NetSysLab.ProtocolBuffers.InternalRequest.Host.Builder, ca.NetSysLab.ProtocolBuffers.InternalRequest.HostOrBuilder> clientBuilder_;
      /**
       * <code>optional .Host client = 1;</code>
       * @return Whether the client field is set.
       */
      public boolean hasClient() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .Host client = 1;</code>
       * @return The client.
       */
      public ca.NetSysLab.ProtocolBuffers.InternalRequest.Host getClient() {
        if (clientBuilder_ == null) {
          return client_ == null ? ca.NetSysLab.ProtocolBuffers.InternalRequest.Host.getDefaultInstance() : client_;
        } else {
          return clientBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Host client = 1;</code>
       */
      public Builder setClient(ca.NetSysLab.ProtocolBuffers.InternalRequest.Host value) {
        if (clientBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          client_ = value;
        } else {
          clientBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional .Host client = 1;</code>
       */
      public Builder setClient(
          ca.NetSysLab.ProtocolBuffers.InternalRequest.Host.Builder builderForValue) {
        if (clientBuilder_ == null) {
          client_ = builderForValue.build();
        } else {
          clientBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional .Host client = 1;</code>
       */
      public Builder mergeClient(ca.NetSysLab.ProtocolBuffers.InternalRequest.Host value) {
        if (clientBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            client_ != null &&
            client_ != ca.NetSysLab.ProtocolBuffers.InternalRequest.Host.getDefaultInstance()) {
            getClientBuilder().mergeFrom(value);
          } else {
            client_ = value;
          }
        } else {
          clientBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional .Host client = 1;</code>
       */
      public Builder clearClient() {
        bitField0_ = (bitField0_ & ~0x00000001);
        client_ = null;
        if (clientBuilder_ != null) {
          clientBuilder_.dispose();
          clientBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .Host client = 1;</code>
       */
      public ca.NetSysLab.ProtocolBuffers.InternalRequest.Host.Builder getClientBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getClientFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Host client = 1;</code>
       */
      public ca.NetSysLab.ProtocolBuffers.InternalRequest.HostOrBuilder getClientOrBuilder() {
        if (clientBuilder_ != null) {
          return clientBuilder_.getMessageOrBuilder();
        } else {
          return client_ == null ?
              ca.NetSysLab.ProtocolBuffers.InternalRequest.Host.getDefaultInstance() : client_;
        }
      }
      /**
       * <code>optional .Host client = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ca.NetSysLab.ProtocolBuffers.InternalRequest.Host, ca.NetSysLab.ProtocolBuffers.InternalRequest.Host.Builder, ca.NetSysLab.ProtocolBuffers.InternalRequest.HostOrBuilder> 
          getClientFieldBuilder() {
        if (clientBuilder_ == null) {
          clientBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ca.NetSysLab.ProtocolBuffers.InternalRequest.Host, ca.NetSysLab.ProtocolBuffers.InternalRequest.Host.Builder, ca.NetSysLab.ProtocolBuffers.InternalRequest.HostOrBuilder>(
                  getClient(),
                  getParentForChildren(),
                  isClean());
          client_ = null;
        }
        return clientBuilder_;
      }

      private ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest request_;
      private com.google.protobuf.SingleFieldBuilderV3<
          ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest, ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest.Builder, ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequestOrBuilder> requestBuilder_;
      /**
       * <code>optional .KVRequest request = 2;</code>
       * @return Whether the request field is set.
       */
      public boolean hasRequest() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .KVRequest request = 2;</code>
       * @return The request.
       */
      public ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .KVRequest request = 2;</code>
       */
      public Builder setRequest(ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
        } else {
          requestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .KVRequest request = 2;</code>
       */
      public Builder setRequest(
          ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .KVRequest request = 2;</code>
       */
      public Builder mergeRequest(ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest value) {
        if (requestBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            request_ != null &&
            request_ != ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest.getDefaultInstance()) {
            getRequestBuilder().mergeFrom(value);
          } else {
            request_ = value;
          }
        } else {
          requestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional .KVRequest request = 2;</code>
       */
      public Builder clearRequest() {
        bitField0_ = (bitField0_ & ~0x00000002);
        request_ = null;
        if (requestBuilder_ != null) {
          requestBuilder_.dispose();
          requestBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .KVRequest request = 2;</code>
       */
      public ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest.Builder getRequestBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .KVRequest request = 2;</code>
       */
      public ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ?
              ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest.getDefaultInstance() : request_;
        }
      }
      /**
       * <code>optional .KVRequest request = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest, ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest.Builder, ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest, ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest.Builder, ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private java.util.List<ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat> heartbeats_ =
        java.util.Collections.emptyList();
      private void ensureHeartbeatsIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          heartbeats_ = new java.util.ArrayList<ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat>(heartbeats_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat, ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat.Builder, ca.NetSysLab.ProtocolBuffers.InternalRequest.HeartbeatOrBuilder> heartbeatsBuilder_;

      /**
       * <code>repeated .Heartbeat heartbeats = 3;</code>
       */
      public java.util.List<ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat> getHeartbeatsList() {
        if (heartbeatsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(heartbeats_);
        } else {
          return heartbeatsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Heartbeat heartbeats = 3;</code>
       */
      public int getHeartbeatsCount() {
        if (heartbeatsBuilder_ == null) {
          return heartbeats_.size();
        } else {
          return heartbeatsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Heartbeat heartbeats = 3;</code>
       */
      public ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat getHeartbeats(int index) {
        if (heartbeatsBuilder_ == null) {
          return heartbeats_.get(index);
        } else {
          return heartbeatsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Heartbeat heartbeats = 3;</code>
       */
      public Builder setHeartbeats(
          int index, ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat value) {
        if (heartbeatsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeartbeatsIsMutable();
          heartbeats_.set(index, value);
          onChanged();
        } else {
          heartbeatsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Heartbeat heartbeats = 3;</code>
       */
      public Builder setHeartbeats(
          int index, ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat.Builder builderForValue) {
        if (heartbeatsBuilder_ == null) {
          ensureHeartbeatsIsMutable();
          heartbeats_.set(index, builderForValue.build());
          onChanged();
        } else {
          heartbeatsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Heartbeat heartbeats = 3;</code>
       */
      public Builder addHeartbeats(ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat value) {
        if (heartbeatsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeartbeatsIsMutable();
          heartbeats_.add(value);
          onChanged();
        } else {
          heartbeatsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Heartbeat heartbeats = 3;</code>
       */
      public Builder addHeartbeats(
          int index, ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat value) {
        if (heartbeatsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeartbeatsIsMutable();
          heartbeats_.add(index, value);
          onChanged();
        } else {
          heartbeatsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Heartbeat heartbeats = 3;</code>
       */
      public Builder addHeartbeats(
          ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat.Builder builderForValue) {
        if (heartbeatsBuilder_ == null) {
          ensureHeartbeatsIsMutable();
          heartbeats_.add(builderForValue.build());
          onChanged();
        } else {
          heartbeatsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Heartbeat heartbeats = 3;</code>
       */
      public Builder addHeartbeats(
          int index, ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat.Builder builderForValue) {
        if (heartbeatsBuilder_ == null) {
          ensureHeartbeatsIsMutable();
          heartbeats_.add(index, builderForValue.build());
          onChanged();
        } else {
          heartbeatsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Heartbeat heartbeats = 3;</code>
       */
      public Builder addAllHeartbeats(
          java.lang.Iterable<? extends ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat> values) {
        if (heartbeatsBuilder_ == null) {
          ensureHeartbeatsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, heartbeats_);
          onChanged();
        } else {
          heartbeatsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Heartbeat heartbeats = 3;</code>
       */
      public Builder clearHeartbeats() {
        if (heartbeatsBuilder_ == null) {
          heartbeats_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          heartbeatsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Heartbeat heartbeats = 3;</code>
       */
      public Builder removeHeartbeats(int index) {
        if (heartbeatsBuilder_ == null) {
          ensureHeartbeatsIsMutable();
          heartbeats_.remove(index);
          onChanged();
        } else {
          heartbeatsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Heartbeat heartbeats = 3;</code>
       */
      public ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat.Builder getHeartbeatsBuilder(
          int index) {
        return getHeartbeatsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Heartbeat heartbeats = 3;</code>
       */
      public ca.NetSysLab.ProtocolBuffers.InternalRequest.HeartbeatOrBuilder getHeartbeatsOrBuilder(
          int index) {
        if (heartbeatsBuilder_ == null) {
          return heartbeats_.get(index);  } else {
          return heartbeatsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Heartbeat heartbeats = 3;</code>
       */
      public java.util.List<? extends ca.NetSysLab.ProtocolBuffers.InternalRequest.HeartbeatOrBuilder> 
           getHeartbeatsOrBuilderList() {
        if (heartbeatsBuilder_ != null) {
          return heartbeatsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(heartbeats_);
        }
      }
      /**
       * <code>repeated .Heartbeat heartbeats = 3;</code>
       */
      public ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat.Builder addHeartbeatsBuilder() {
        return getHeartbeatsFieldBuilder().addBuilder(
            ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat.getDefaultInstance());
      }
      /**
       * <code>repeated .Heartbeat heartbeats = 3;</code>
       */
      public ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat.Builder addHeartbeatsBuilder(
          int index) {
        return getHeartbeatsFieldBuilder().addBuilder(
            index, ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat.getDefaultInstance());
      }
      /**
       * <code>repeated .Heartbeat heartbeats = 3;</code>
       */
      public java.util.List<ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat.Builder> 
           getHeartbeatsBuilderList() {
        return getHeartbeatsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat, ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat.Builder, ca.NetSysLab.ProtocolBuffers.InternalRequest.HeartbeatOrBuilder> 
          getHeartbeatsFieldBuilder() {
        if (heartbeatsBuilder_ == null) {
          heartbeatsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat, ca.NetSysLab.ProtocolBuffers.InternalRequest.Heartbeat.Builder, ca.NetSysLab.ProtocolBuffers.InternalRequest.HeartbeatOrBuilder>(
                  heartbeats_,
                  ((bitField0_ & 0x00000004) != 0),
                  getParentForChildren(),
                  isClean());
          heartbeats_ = null;
        }
        return heartbeatsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:InternalRequestWrapper)
    }

    // @@protoc_insertion_point(class_scope:InternalRequestWrapper)
    private static final ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper();
    }

    public static ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InternalRequestWrapper>
        PARSER = new com.google.protobuf.AbstractParser<InternalRequestWrapper>() {
      @java.lang.Override
      public InternalRequestWrapper parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<InternalRequestWrapper> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InternalRequestWrapper> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ca.NetSysLab.ProtocolBuffers.InternalRequest.InternalRequestWrapper getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Host_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Host_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Heartbeat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Heartbeat_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InternalRequestWrapper_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InternalRequestWrapper_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"src/protobuf/InternalRequest.proto\032\"sr" +
      "c/protobuf/KeyValueRequest.proto\" \n\004Host" +
      "\022\n\n\002ip\030\001 \001(\014\022\014\n\004port\030\002 \001(\005\"A\n\tHeartbeat\022" +
      "\023\n\004host\030\001 \001(\0132\005.Host\022\n\n\002id\030\002 \001(\005\022\023\n\013epoc" +
      "hMillis\030\003 \001(\003\"\215\001\n\026InternalRequestWrapper" +
      "\022\032\n\006client\030\001 \001(\0132\005.HostH\000\210\001\001\022 \n\007request\030" +
      "\002 \001(\0132\n.KVRequestH\001\210\001\001\022\036\n\nheartbeats\030\003 \003" +
      "(\0132\n.HeartbeatB\t\n\007_clientB\n\n\010_requestB/\n" +
      "\034ca.NetSysLab.ProtocolBuffersB\017InternalR" +
      "equestb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ca.NetSysLab.ProtocolBuffers.KeyValueRequest.getDescriptor(),
        });
    internal_static_Host_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Host_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Host_descriptor,
        new java.lang.String[] { "Ip", "Port", });
    internal_static_Heartbeat_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Heartbeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Heartbeat_descriptor,
        new java.lang.String[] { "Host", "Id", "EpochMillis", });
    internal_static_InternalRequestWrapper_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_InternalRequestWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InternalRequestWrapper_descriptor,
        new java.lang.String[] { "Client", "Request", "Heartbeats", "Client", "Request", });
    ca.NetSysLab.ProtocolBuffers.KeyValueRequest.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
